export function createEmptyGrille<T>(clazz: new (...args: any[]) => T): T[][] {
  return [
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
    [
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
      new clazz(),
    ],
  ]
}
